export const predefinedKPIs = [
    "Communication",
    "Learning Curve",
    "Understanding",
    "Capability",
    "Task Completion",
    "Requirement Gathering",
    "Coding Skill",
    "In-depth Knowledge",
    "Experience",
    "Problem Solving",
    "Presentation",
    "Code Quality",
    "Concepts",
    "Contribution",
    "Logical Thinking",
    "Technical Proficiency",
    "Project Presentation",
    "Scenario-Based Questions",
    "Documentation",
    "QA Evaluation",
    "Code Complexity",
  ];