export const skillOptions = [
    { value: "ReactJS", label: "ReactJS" },
    { value: "Angular", label: "Angular" },
    { value: "VueJS", label: "VueJS" },
    { value: "Svelte", label: "Svelte" },
    { value: "Next.js", label: "Next.js" },
    { value: "Nuxt.js", label: "Nuxt.js" },
    { value: "HTML/CSS", label: "HTML/CSS" },
    { value: "SASS/SCSS", label: "SASS/SCSS" }, 
    { value: "Tailwind CSS", label: "Tailwind CSS" },
    { value: "Bootstrap", label: "Bootstrap" },
    { value: "Material-UI", label: "Material-UI" },
    { value: "JavaScript", label: "JavaScript" },
    { value: "TypeScript", label: "TypeScript" },
    { value: "Node.js", label: "Node.js" },
    { value: "Express.js", label: "Express.js" },
    { value: "Prisma", label: "Prisma" },
    { value: "NestJS", label: "NestJS" },
    { value: "Django", label: "Django" },
    { value: "fastify", label: "fastify" },
    { value: "Flask", label: "Flask" },
    { value: "FastAPI", label: "FastAPI" },
    { value: "Spring Boot", label: "Spring Boot" },
    { value: "Ruby on Rails", label: "Ruby on Rails" },
    { value: "PHP", label: "PHP" },
    { value: "Laravel", label: "Laravel" },
    { value: "Python", label: "Python" },
    { value: "Java", label: "Java" },
    { value: "C#", label: "C#" },
    { value: "C++", label: "C++" },
    { value: "Go", label: "Go" },
    { value: "Rust", label: "Rust" },
    { value: "Swift", label: "Swift" },
    { value: "Kotlin", label: "Kotlin" },
    { value: "Dart", label: "Dart" },
    { value: "Flutter", label: "Flutter" },
    { value: "React Native", label: "React Native" },
    { value: "Electron.js", label: "Electron.js" },
    { value: "MySQL", label: "MySQL" },
    { value: "PostgreSQL", label: "PostgreSQL" },
    { value: "MariaDB", label: "MariaDB" },
    { value: "MongoDB", label: "MongoDB" },
    { value: "Redis", label: "Redis" },
    { value: "Firebase", label: "Firebase" },
    { value: "DynamoDB", label: "DynamoDB" },
    { value: "Cassandra", label: "Cassandra" },
    { value: "Neo4j", label: "Neo4j" },
    { value: "Elasticsearch", label: "Elasticsearch" },
    { value: "Supabase", label: "Supabase" },
    { value: "AWS", label: "AWS" },
    { value: "Azure", label: "Azure" },
    { value: "Google Cloud", label: "Google Cloud" },
    { value: "Heroku", label: "Heroku" },
    { value: "Vercel", label: "Vercel" },
    { value: "Netlify", label: "Netlify" },
    { value: "Docker", label: "Docker" },
    { value: "Kubernetes", label: "Kubernetes" },
    { value: "Terraform", label: "Terraform" },
    { value: "Jenkins", label: "Jenkins" },
    { value: "GitHub Actions", label: "GitHub Actions" },
    { value: "CircleCI", label: "CircleCI" },
    { value: "TravisCI", label: "TravisCI" },
    { value: "CI/CD", label: "CI/CD" },
    { value: "Git", label: "Git" },
    { value: "Bitbucket", label: "Bitbucket" },
    { value: "GitLab", label: "GitLab" },
    { value: "JIRA", label: "JIRA" },
    { value: "Selenium", label: "Selenium" },
    { value: "Cypress", label: "Cypress" },
    { value: "Playwright", label: "Playwright" },
    { value: "Puppeteer", label: "Puppeteer" },
    { value: "Appium", label: "Appium" },
    { value: "JUnit", label: "JUnit" },
    { value: "TestNG", label: "TestNG" },
    { value: "Mocha", label: "Mocha" },
    { value: "Jest", label: "Jest" },
    { value: "Chai", label: "Chai" },
    { value: "PyTest", label: "PyTest" },
    { value: "Postman", label: "Postman" },
    { value: "J-meter", label: "J-meter" },
    { value: "GraphQL", label: "GraphQL" },
    { value: "REST API", label: "REST API" },
    { value: "gRPC", label: "gRPC" },
    { value: "Microservices", label: "Microservices" },
    { value: "Event-Driven Architecture", label: "Event-Driven Architecture" },
    { value: "RabbitMQ", label: "RabbitMQ" },
    { value: "Kafka", label: "Kafka" },
    { value: "Nginx", label: "Nginx" },
    { value: "Apache", label: "Apache" },
    { value: "Cybersecurity", label: "Cybersecurity" },
    { value: "Machine Learning", label: "Machine Learning" },
    { value: "Deep Learning", label: "Deep Learning" },
    { value: "Data Structures", label: "Data Structures" },
    { value: "Algorithm techniques", label: "Algorithm techniques" },
    { value: "AI/ML", label: "AI/ML" },
    { value: "MLOps", label: "MLOps" },
    { value: "Computer Vision", label: "Computer Vision" },
    { value: "NLP", label: "NLP" },
    { value: "Blockchain", label: "Blockchain" },
    { value: "Solidity", label: "Solidity" },
    { value: "Ethereum", label: "Ethereum" },
    { value: "Web3.js", label: "Web3.js" },
    { value: "Three.js", label: "Three.js" },
    { value: "Unity", label: "Unity" },
    { value: "Unreal Engine", label: "Unreal Engine" }
];
